# Generated by Django 4.2.28 on 2026-03-24 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prestation_type', models.CharField(max_length=50)),
                ('selected_plan_id', models.CharField(max_length=50)),
                ('selected_plan_title', models.CharField(max_length=100)),
                ('selected_plan_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selected_plan_duration', models.CharField(max_length=20)),
                ('reservation_date', models.DateField()),
                ('time_slot', models.CharField(max_length=10)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('adresse', models.TextField()),
                ('ville', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=10)),
                ('code_promo', models.CharField(blank=True, max_length=50, null=True)),
                ('autres_informations', models.TextField(blank=True, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplementaryService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=20)),
                ('price_discounted', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_original', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField(default=1)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplementary_services', to='core.reservation')),
            ],
            options={
                'unique_together': {('reservation', 'service_id')},
            },
        ),
    ]
