# Generated by Django 4.2.28 on 2026-03-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_slot', models.CharField(blank=True, help_text='Leave empty to block the entire day', max_length=10, null=True)),
                ('reason', models.CharField(blank=True, help_text="Optional reason for the leave (e.g., 'Holiday', 'Sick leave')", max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Congé',
                'verbose_name_plural': 'Congés',
                'ordering': ['-date', 'time_slot'],
                'unique_together': {('date', 'time_slot')},
            },
        ),
    ]
