# Generated by Django 4.2.28 on 2026-03-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_conge'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='supplementary_services',
            field=models.JSONField(blank=True, default=list, help_text='List of supplementary services as JSON array'),
        ),
        migrations.DeleteModel(
            name='SupplementaryService',
        ),
    ]
