# Generated by Django 4.2.28 on 2026-03-26 15:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_reservation_supplementary_services_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique promo code', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the promo code', null=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Discount value (percentage or fixed amount)', max_digits=10)),
                ('minimum_amount', models.DecimalField(decimal_places=2, default=0, help_text='Minimum order amount to apply promo', max_digits=10)),
                ('max_uses', models.IntegerField(default=0, help_text='Maximum number of uses (0 = unlimited)')),
                ('used_count', models.IntegerField(default=0, help_text='Number of times this promo has been used')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this promo code is active')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, help_text='When the promo becomes valid')),
                ('valid_until', models.DateTimeField(blank=True, help_text='When the promo expires (optional)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promo Code',
                'verbose_name_plural': 'Promo Codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount amount applied', max_digits=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Original price before discount', max_digits=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='promo_code_applied',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='core.promocode'),
        ),
    ]
