# Generated by Django 4.2.28 on 2026-03-27 09:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_promocode_max_uses_unlimited_null'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocode',
            options={'ordering': ['-created_at'], 'verbose_name': 'Code promo', 'verbose_name_plural': 'Codes promo'},
        ),
        migrations.AlterField(
            model_name='conge',
            name='reason',
            field=models.CharField(blank=True, help_text="Motif facultatif du congé (ex: 'Vacances', 'Maladie')", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='conge',
            name='time_slot',
            field=models.CharField(blank=True, help_text='Laisser vide pour bloquer toute la journée', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(help_text='Code promo unique', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='description',
            field=models.TextField(blank=True, help_text='Description du code promo', null=True),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Pourcentage'), ('fixed', 'Montant fixe')], default='percentage', max_length=20),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, help_text='Valeur de la remise (pourcentage ou montant fixe)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indique si ce code promo est actif'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='max_uses',
            field=models.IntegerField(blank=True, default=None, help_text="Nombre maximal d'utilisations (U = illimité, 0 = jamais)", null=True),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='minimum_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant minimum de commande pour appliquer le code promo', max_digits=10),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='used_count',
            field=models.IntegerField(default=0, help_text='Nombre de fois où ce code promo a été utilisé'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='valid_from',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date/heure de début de validité du code promo'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='valid_until',
            field=models.DateTimeField(blank=True, help_text='Date/heure de fin de validité du code promo (facultatif)', null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant de remise appliqué', max_digits=10),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Prix initial avant remise', max_digits=10),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('cancelled', 'Annulée'), ('completed', 'Terminée')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='supplementary_services',
            field=models.JSONField(blank=True, default=list, help_text='Liste des prestations supplémentaires au format JSON'),
        ),
    ]
