# Generated by Django 4.2.28 on 2026-03-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_promocode_options_alter_conge_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlotCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_time_slots_per_day', models.PositiveIntegerField(default=9, help_text='Max créneaux autorisés par jour (ex: 3 => complété après 3 réservations).')),
                ('is_active', models.BooleanField(default=True, help_text="Seul l'élément actif est utilisé.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Limite créneaux/jour',
                'verbose_name_plural': 'Limites créneaux/jour',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
