# Generated by Django 4.2.28 on 2026-03-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_timeslotcapacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslotcapacity',
            name='max_time_slots_per_day',
        ),
        migrations.AddField(
            model_name='timeslotcapacity',
            name='Max_réservations_actives_pour_un_même_créneau',
            field=models.PositiveIntegerField(default=9, help_text='Max réservations actives pour un même créneau (date+heure). Ex: 3 => complet après 3 réservations.'),
        ),
    ]
