# Generated by Django 4.2.28 on 2026-03-31 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_timeslotcapacity_max_time_slots_per_day_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslotcapacity',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Capacité de créneaux', 'verbose_name_plural': 'Capacités de créneaux'},
        ),
        migrations.AlterField(
            model_name='timeslotcapacity',
            name='Max_réservations_actives_pour_un_même_créneau',
            field=models.PositiveIntegerField(default=9),
        ),
    ]
